version: '3'
services:
  site:
    build: ./
    container_name: estebanco_pug_1
    volumes:
      - ./www:/var/www
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "3001:3001"
